### ISSUE TITLE
App is not using Wifi network (Android)

### ISSUE THREAD

**Issue by JohnMaguire** [florian-guillemard/WiFiFlutter#219]
Hi there. I'm trying to use wifi_iot to connect to a phone camera and pull images from it. I have the following code in a model:

```
  Future<bool> connect(String password) async {
    return await WiFiForIoTPlugin.connect(network.ssid!,
        joinOnce: true, password: password, security: NetworkSecurity.WPA);
  }
```

When I call this method, Android asks me if I'd like to connect (and at this point, the function seems to return early - a second bug I haven't dug into yet). I choose yes, and then it takes a moment to connect. I then try to load photos from a local IP address (192.168.0.1), but this fails.

If I manually connect to the Wifi network instead, I'm able to load photos.

I then saw that there's a `forceWifiUsage` method, so I added that code after the connection attempt:

```
try {
  if (await WiFiForIoTPlugin.forceWifiUsage(true) != true) {
    throw Exception("Failed to use camera connection");
  }

  _photos = await _client.listPhotos();

  if (await WiFiForIoTPlugin.forceWifiUsage(false) != true) {
    throw Exception("Failed to stop using camera connection");
  }
} catch (e) {
  _errorText = e.toString();
} finally {
  _setLoading(false);
}
```

This still doesn't work - even if I refresh after the system finishes connecting to the Wifi network. If I navigate to Android Wifi settings it tells me that the network is in use by my app.

When looking at the Android docs, it seems I need to specify the network I want to force use of, but wifi_iot doesn't seem to offer this functionality: https://developer.android.com/reference/android/net/ConnectivityManager#bindProcessToNetwork(android.net.Network)

Any help would be appreciated.

**Comment by daadu** [comment]
@JohnMaguire Your code and configuration seems correct. `forceWifiUsage` - forces the current network. 

Can you share the logs for debugging?

Also,
- Does the network you connect to have internet available?
- Are you sure -  the app is configured to allow "clear text traffic"?

**Comment by JohnMaguire** [comment]
Hi @daadu - thanks for the confirmation. This is my first time working on an Android app, and I'm not quite sure where to find the debug logs for wifi_iot. I'll see what I can find online and post here when I figure it out.

In the meantime - the network does *not* have internet available, and I think this is a part of the issue. Since it's a camera, it just exposes a local HTTP web server on 192.168.0.1. There is no internet connection. This is perhaps why I am looking for this API: https://developer.android.com/reference/android/net/ConnectivityManager#bindProcessToNetwork(android.net.Network)

I will make sure cleartext traffic is enabled, but just to reiterate from my original post, I am able to load the photos if I connect to the WiFi network via the Android settings and tell it to stay connected despite the lack of internet connection.

**Comment by JohnMaguire** [comment]
OK, so I tried again today and the behavior is a little different than I was experiencing before - perhaps at least partially due to a full reinstall of the app instead of a hot refresh? If I see the issue again, I'll report back. For now I'll close the issue.

One thing that was throwing me off is that if you are already connected to the network specified in `WiFiForIoTPlugin.connect` it seems to reconnect (system dialogs asking the user for confirmation) while simultaneously immediately returning. This results in confusion behavior where the app is moving behind the system dialog, but the system dialog is prompting the user for confirmation.

The rest of my issues seem to have come down to an issue around calling `ScaffoldMessenger.of(context)` / `Navigator.of(context)` in an invalid place. I solved it by moving those calls above the component whose callback used them, since that component has already been disposed by the time the code executes (which I hope is correct):

```
      onPressed: () {
        showDialog(
            context: context,
            builder: (context) {
              final scaffoldMessenger = ScaffoldMessenger.of(context);
              final navigator = Navigator.of(context);

              return PasswordPrompt(
                  ssid: network.ssid,
                  onSubmit: (value) async {
                    final connected = await network.connect(value);
                    if (!connected) {
                      scaffoldMessenger.showSnackBar(
                          const SnackBar(content: Text('Failed to connect')));
                      return;
                    }

                    scaffoldMessenger.showSnackBar(
                        const SnackBar(content: Text('Connected')));
                    navigator.pushNamed('/camera-photos');
                  });
            });
      },
```
